### ISSUE TITLE
Issues with zero package

### ISSUE THREAD

**Issue by rruizdeaustri** [Yura52/tabular-dl-revisiting-models#19]
Hi,

I'm trying to run the mlp.py model but I have issues with the zero package. Functions like iloader, set_randomness does not exist in the GitHub version. 

Best,
Rbt

**Comment by Yura52** [comment]
Hi, make sure that you follow [these step](https://github.com/Yura52/tabular-dl-revisiting-models#31-pytorch-environment) when setting up the environment. In particular, you should have `libzero==0.0.3.dev7` (see [requirements.txt](https://github.com/Yura52/tabular-dl-revisiting-models/blob/f65a93329a58c80ea486a212feeba6babf9fdd4f/requirements.txt#L4)).

**Comment by Yura52** [comment]
Feel free to reopen the issue if help is needed!
