### ISSUE TITLE
Data encoding 

### ISSUE THREAD

**Issue by rruizdeaustri** [Yura52/tabular-dl-revisiting-models#20]
Hi Yura, 

Sorry for my late reply. 

Your instructions to install the package and dependences worked !

Since it works I want to apply it to particle physics data similar to the Higgs data but in this case I have categorical entrances as well and I need to process them to convert them to something that is compatible with the package. I mean to have N_train.npy, C_train.npy, etc .. files

Is there any utility that could help me in doing this out of the box ?

Thanks a lot !!

Rbt

**Comment by Yura52** [comment]
Hi! Unfortunately, we do not provide such a utility. I recommend reading [this comment](https://github.com/Yura52/tabular-dl-revisiting-models/issues/3#issuecomment-1068124334), it can be helpful.

**Comment by Yura52** [comment]
P.S. Also, check out our new paper ["On Embeddings for Numerical Features in Tabular Deep Learning"](https://github.com/Yura52/tabular-dl-num-embeddings). It can be the case that the new models we describe there can be useful for your task as well.

**Comment by rruizdeaustri** [comment]
Hi Yura,

Thanks a lot for the advice !!

**Comment by Yura52** [comment]
Feel free to reopen the issue if help is needed.
