### ISSUE TITLE
Is there any pre-processing in the data?

### ISSUE THREAD

**Issue by imasojeong** [Yura52/tabular-dl-revisiting-models#25]
Is there any pre-processing in the data?

**Comment by Yura52** [comment]
The preprocessing strategy can be selected in the config. For example, see this config:
https://github.com/Yura52/tabular-dl-revisiting-models/blob/f65a93329a58c80ea486a212feeba6babf9fdd4f/output/adult/mlp/tuned/11.toml#L3

In this example, numerical features are preprocessed using the quantile transformation, and categorical features are encoded with their indices (think `sklearn.preprocessing.OrdinalEncoder`).

Does this answer your question?
