### ISSUE TITLE
Question about MI dataset

### ISSUE THREAD

**Issue by fingertap** [Yura52/tabular-dl-revisiting-models#33]
In your paper, you said the MI dataset (i.e., the [LETOR 4.0](https://www.microsoft.com/en-us/research/project/letor-learning-rank-information-retrieval/letor-4-0/) dataset has a dimensionality of 136. However, I find that both `MQ2007` and `MQ2008` in this data set are 46-dimensional. What do I miss here?

**Comment by Yura52** [comment]
Hi! We used the [MSLR-10K dataset](https://www.microsoft.com/en-us/research/project/mslr), it is a different one. I guess the confusion comes from the fact that we cite the paper "Introducing LETOR 4.0 Datasets", however on the page that I linked it is the recommended reference (I don't know why :) ).

P.S. I assumed that the question was about the paper "Revisiting Deep Learning Models for Tabular Data". If not, please let me know.

**Comment by fingertap** [comment]
Thanks. This address my problem.
