### ISSUE TITLE
Dataset link not working ？

### ISSUE THREAD

**Issue by ZhaoShengjian** [Yura52/tabular-dl-revisiting-models#35]
The dataset link you provided （https://www.dropbox.com/s/o53umyg6mn3zhxy/data.tar.gz?dl=1）
doesn't seem to be able to be downloaded, can you check it for an update, thank you.

**Comment by Yura52** [comment]
The link from README works for me, so maybe the reason is that your machine cannot connect to DropBox for some reason?

**Comment by WuZheng326** [comment]
I also met this problem. Maybe the dataset link is not stable. I can link in the homepage of dropbox but the dataset link is not available to reach. Actually I once linked in the website and start to download the dataset. But failed while downloading. After that the link cannot be linked in.

**Comment by Kunkka007** [comment]
the same problem, please fix this error, thanks :)

**Comment by Yura52** [comment]
@ZhaoShengjian  @WuZheng326 @Kunkka007 Previously, I could not reproduce the issue (the link worked properly at least on two different machines). However, this time, I confirm the issue, I will let you know once it is fixed.

**Comment by Yura52** [comment]
Hi @ZhaoShengjian @WuZheng326 @Kunkka007 

The link seems to be working again, could you confirm that?
