### ISSUE TITLE
How to import my own dataset with your model?

### ISSUE THREAD

**Issue by mf093087** [Yura52/tabular-dl-revisiting-models#37]
I have a new dataset. Could you please tell me how I can use your model to train and test my dataset? Thanks a lot in advance! My feature data is (9000, 7), and the target is multi classification.

**Comment by Yura52** [comment]
Does [this comment](https://github.com/Yura52/tabular-dl-revisiting-models/issues/3#issuecomment-1068124334) answer your question?

**Comment by Yura52** [comment]
Feel free to reopen the issue if needed
