### ISSUE TITLE
Can you suggest me the proper way to referencing this library?

### ISSUE THREAD

**Issue by sappho192** [Yura52/tabular-dl-revisiting-models#41]
Hi, thank you for sharing this great implementation :)

I want to refer this library when I make my own application with this library and write the paper, but it's little bit hard to me to decide which paper to cite.

Since my code will be based on current version of the library, is it okay to cite your latest paper, `rubachev2022revisiting`? Or just citing the original paper, `gorishniy2021revisiting` is okay?

**Comment by Yura52** [comment]
Hi! This repository is dedicated solely to the paper "Revisiting Deep Learning Models for Tabular Data", so you should cite this paper.

Other links:
- the repository for "On Embeddings for Numerical Features in Tabular Deep Learning" is located [here](https://github.com/Yura52/tabular-dl-num-embeddings)
- the repository for "Revisiting Pretraining Objectives for Tabular Deep Learning" is located [here](https://github.com/puhsu/tabular-dl-pretrain-objectives)
- the repository of the pip-installable package for "Revisiting Deep Learning Models for Tabular Data" is located [here](https://github.com/Yura52/rtdl)

**Comment by sappho192** [comment]
Oops! I thought I created this issue on [rtdl](https://github.com/Yura52/rtdl) but I was wrong.
(But it seems that I should still cite the same paper)

Thank you :)

**Comment by Yura52** [comment]
That's right, you should cite the "Revisiting Deep Learning Models for Tabular Data" :)
